
'#INCLUDE "serial.h"
'InitPPSSerial
'
'HSerPrint ADCVal
'
'HSerPrintCRLF


    'Generated by PIC PPS Tool for Great Cow Basic
    'PPS Tool version: 0.0.6.2
    'PinManager data: v1.81.0
    'Generated for 18f16q41
    '
    'Template comment at the start of the config file
    '
    #startup InitPPSSerial, 85
    #define PPSToolPart 18f16q41

    Sub InitPPSSerial

            'Module: UART pin directions
            Dir PORTC.6 Out    ' Make TX1 pin an output
            'Module: UART1
            RC6PPS = 0x0010    'TX1 > RC6

    End Sub
    'Template comment at the end of the config file

'USART settings for USART1
#define USART_BAUD_RATE 9600
#define USART_TX_BLOCKING
#define USART_DELAY OFF
